/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppRoutinesRouteImport } from './routes/_app.routines'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppExternalRequestsRouteImport } from './routes/_app.external-requests'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExternalRequestsRoute = AppExternalRequestsRouteImport.update({
  id: '/external-requests',
  path: '/external-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/external-requests': typeof AppExternalRequestsRoute
  '/inventory': typeof AppInventoryRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/routines': typeof AppRoutinesRoute
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/dashboard': typeof AppDashboardRoute
  '/external-requests': typeof AppExternalRequestsRoute
  '/inventory': typeof AppInventoryRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/routines': typeof AppRoutinesRoute
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/external-requests': typeof AppExternalRequestsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/external-requests'
    | '/inventory'
    | '/opportunities'
    | '/profile'
    | '/roles'
    | '/routines'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/external-requests'
    | '/inventory'
    | '/opportunities'
    | '/profile'
    | '/roles'
    | '/routines'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/announcements'
    | '/_app/dashboard'
    | '/_app/external-requests'
    | '/_app/inventory'
    | '/_app/opportunities'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/routines'
    | '/_app/tasks'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/external-requests': {
      id: '/_app/external-requests'
      path: '/external-requests'
      fullPath: '/external-requests'
      preLoaderRoute: typeof AppExternalRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExternalRequestsRoute: typeof AppExternalRequestsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRolesRoute: typeof AppRolesRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExternalRequestsRoute: AppExternalRequestsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProfileRoute: AppProfileRoute,
  AppRolesRoute: AppRolesRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppTasksRoute: AppTasksRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
